Updates and tweaks to run-java-tool.
svn path=/java-config-ng/branches/axxo/; revision=2393

diff --git a/src/run-java-tool b/src/run-java-tool
--- a/src/run-java-tool
+++ b/src/run-java-tool
@@ -1,27 +1,39 @@
 #!/bin/bash
 
+user_vm="${HOME}/.gentoo/java-config-2/current-user-vm"
+system_vm="/etc/java-config-2/current-system-vm"
+# Try GENTOO_VM
 if [[ -n ${GENTOO_VM} ]]; then
-	vmpath=/usr/lib/jvm/${GENTOO_VM}/
-elif [[ -h ${HOME}/.gentoo/java-config-2/current-user-vm ]]; then
-	vmpath=${HOME}/.gentoo/java-config-2/current-user-vm/
+	vmpath="/usr/lib/jvm/${GENTOO_VM}/"
+# Then user VM
+elif [[ -h ${user_vm} ]]; then
+	vmpath=$(readlink ${user_vm})
+# And fall back to the system VM
 else
-	vmpath=/etc/java-config-2/current-system-vm/
+	vmpath=$(readlink ${system_vm})
 fi
 tool=$(basename $0)
 bin=${vmpath}/bin/${tool}
 jrebin=${vmpath}/jre/bin/${tool}
 
+vm_handle=$(basename ${vmpath})
 if [[ -x ${bin} ]]; then 
 	exec ${bin} "${@}"
 elif [[ -x ${jrebin} ]]; then
 	exec ${jrebin} "${@}"
 else
 	if [[ ! -d ${vmpath} ]]; then
-		echo "Could not find: ${vmpath}" >&2
-		echo "Wrong system/user vm or GENTOO_VM" >&2
+		echo "Home for VM '${vm_handle}' does not exist: ${vmpath}" >&2
+        if [[ -n ${GENTOO_VM} ]]; then
+            echo "Invalid value for GENTOO_VM: ${GENTOO_VM}"
+        elif [[ -h ${user_vm} ]]; then
+            echo "Invalid User VM: ${vm_handle}" >&2
+        else
+            echo "Invalid System VM: ${vm_handle}" >&2
+        fi
 	else
-		echo "Want too run ${vmpath}/{,jre}/bin/${tool} but it does not exist or is not executable" >&2
-		echo "Broken vm install" >&2
+        echo "Tried to execute ${bin} and ${jrebin}, but neither exist." >&2
+        echo "Perhaps there is something wrong with the install of ${vm_handle}?" >&2
 	fi
 	exit 1
 fi
